version:          "3.4"

x-env-files:      &env-files
  env_file:
    - .env

services:
  mysql-manager-1:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndb_mgmd
    container_name: mysql-manager-1

  mysql-manager-2:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndb_mgmd
    container_name: mysql-manager-2

  data-node-1:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndbd
    container_name: data-node-1

  data-node-2:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      ndbd
    container_name: data-node-2

  mysql-server-1:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      mysqld --server-id=11
    ports:
      - 3306:3306
    container_name: mysql-server-1

  mysql-server-2:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      mysqld --server-id=12
    ports:
      - 3307:3306
    container_name: mysql-server-2

  mysql-tester:
    image:        mysql-cluster-configured:8.0
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      sleep infinity
    container_name: mysql-tester

  phpmyadmin:
    image:        phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql-server-1
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
      - MYSQL_ROOT_PASSWORD=rootpass
    networks:
      - db-network
    ports:
      - 50080:80
    restart:      always
    container_name: phpmyadmin

networks:
  db-network:
